"""Added game type column to clubs table

Revision ID: 2d2525b773e
Revises: 2fe92b087948
Create Date: 2014-03-07 14:10:43.691612

"""

# revision identifiers, used by Alembic.
revision = '2d2525b773e'
down_revision = '2fe92b087948'

import sys
import os

from alembic import op
import sqlalchemy as sa

BASEDIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
if BASEDIR not in sys.path:
    sys.path.insert(0, BASEDIR)

from app import models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('game', models.UnicodeTextChoices, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'game')
    ### end Alembic commands ###
