"""Add timezone to Geo models

Revision ID: 511aee157fa9
Revises: 46ba80c4f57b
Create Date: 2014-03-27 10:37:25.186727

"""

# revision identifiers, used by Alembic.
revision = '511aee157fa9'
down_revision = '46ba80c4f57b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'club', sa.Column('timezone', sa.UnicodeText(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'club', 'timezone')
    ### end Alembic commands ###
