"""Make Club game and name not nullable

Revision ID: 57f4d36e0adf
Revises: 32390282bd93
Create Date: 2014-03-23 22:37:51.295301

"""

# revision identifiers, used by Alembic.
revision = '57f4d36e0adf'
down_revision = '32390282bd93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club', 'game',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('club', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('club', 'game',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###
